- name: Setup benchmarks
  hosts: controllers
  gather_facts: true
  vars:
    osu_bench_ver: "5.6.3"
    mpi_module: "mpi/openmpi"
  tasks:
  - name: Create a directory if it does not exist
    file:
      path: "{{ ansible_env.HOME }}/workspace"
      state: directory
  - import_tasks: tasks/benchmarks/download_osu_benchmarks_tasks.yml
  - import_tasks: tasks/benchmarks/download_mpibench_tasks.yml