- name: Install nfs-utils
  become: yes
  yum:
    name:
      - nfs-utils
    state: latest
- name: Start and enable rpcbind
  become: yes
  service:
    name: rpcbind
    state: started
    enabled: yes
- name: Start and enable nfs-server
  become: yes
  service:
    name: nfs-server
    state: started
    enabled: yes
- name: Start and enable nfs-lock
  become: yes
  service:
    name: nfs-lock
    state: started
    enabled: yes
- name: Start and enable nfs-idmap
  become: yes
  service:
    name: nfs-idmap
    state: started
    enabled: yes
- name: Create nfs workspace dir
  file:
    path: "{{ ansible_env.HOME }}/workspace"
    state: directory
- name: Set nfs exports
  become: yes
  shell: |
    echo "{{ ansible_env.HOME }}/workspace *(rw,sync,no_root_squash,no_all_squash)" >> /etc/exports
- name: Restart nfs-server
  become: yes
  service:
    name: nfs-server
    state: restarted
    enabled: yes